- .travis.yml
> Check html validity

- _includes/components/hero.html
- contact.md
> Override hero so it can be just an image bar. Fix #11

- _news/2017-03-25-upsetr-preprint-posted.md
- news.md
> news date and blurb

- news.md
@ngehlenborg : I shouldn't have gotten distracted by this, and it doesn't quite do what you want, but do think that in January of 2018 you'll want a solution for multiple years on the news page?
> Checkpoint: years

- README.md
- _layouts/news.html
Might fix #73? @ngehlenborg : Here's one idea about where to put the date on this page, but it's not something I feel strongly about.
> Include date in title: Not sure I like this style

- _includes/meta.html
- index.md
Clicking through the other pages and they still look good.
> Home page has a title now.

- _members/nichole-parker.md
Nichole will get us a picture soon. Using placeholder for now.
> Add Nichole's page

- _includes/components/hero.html
> Make "view position details" visible

- _projects/hubmap.md
Maybe we want to add something like this? Your call... Feel free to edit, or delegate, whichever is easier. I have not created a separate page from the prov work, but feel like it's worth mentioning?
Fix #176 
Would you also like to add a link on the "Themes" page, under "Visual Exploration of Data Repositories"?
> Stub for HuBMAP portal page

- _data/media.yml
> Add link to phys.org

- _members/chuck-mccallum.md
- _members/claudia-meyer.md
- _members/ilan-gold.md
- _members/jennifer-marx.md
- _members/justine-shih.md
- _members/ziyi-hou.md
- members.md
(I've asked Sehi and Mark to update themselves, and I'll ask Chris for text.)
> add alumni

- _members/chris-briggs.md
> Add Chris to Gehlenborg Lab members

- _news/2020-11-01-os-contributions.md
Are the descriptions of your work accurate? Is my example too trivial? Anyone else in the lab we should nudge to add a line?
> News about OSS contributions

- _projects/tableschema-to-template.md
I think you said posting here wouldn't be out of line? It's not that interesting, but whatever you think best.
> add ts2xl to projects

- _positions/hubmap-intern.md
- _positions/hubmap-senior-bioinformatician.md
Pasted text; added a "more details" link at the bottom.
> Add a page for hubmap internship

- _projects/gosling.md
- _themes/genome-data-visualization.md
> Add Gosling project

- _members/tessa-han.md
(I merged Tessa's PR without a passing build by mistake!)
> Fix yaml formatting

- _publications/lyi-2021-gosling-osf.md
> Add Gosling as accepted paper

- .github/workflows/deploy.yml
Setting `bundler-cache: true` automatically runs `bundle install`.
> John conroy/workflow caching

- _includes/publication-row.html
> Fix markdown in publications list

- _positions/postdoc-biomedical-data-viz.md
> Add postdoc postion

- _includes/publication-row.html
> Fix publications word break

- _positions/senior-ui-ux-designer.md
[HMP-83] Adds Senior UI/UX position on the Lab Website
[HMP-83]: https://hms-dbmi.atlassian.net/browse/HMP-83?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Adds posting for Senior UI/UX Designer position

- _members/fritz-lekschas.md
- _members/furui-cheng.md
- _members/katrina-liu.md
- _members/nichole-parker.md
Update Nichole's title and move Fritz, Furui, and Katrina to alumni.
> Update status of members.

- _data/collaborators.yml
- _members/cynthia-rosas.md
- _members/fritz-lekschas.md
- _members/jennifer-marx.md
- _members/pj-vancamp.md
- _members/roselkis-morla.md
- _members/yousry-elsadec.md
- _news/2020-10-20-ieee-vis-bests.md
Spelling updates for better support for screen reader users and people with cognitive disabilities
> update typos for accessibility

- _members/nichole-parker.md
> Update Nichole's status

- _members/jennifer-chen.md
Adding Jen Chen to the website
> Adding Jen Chen

- _members/jennifer-chen.md
- _publications/moerth-2024-hybrid-approach-osf.md
Updated Eric's name on hybrid publication listing to fix reference to member page.
> Website build fixes

- publications.md
> Sort preprints by year

- _members/evan-biederstedt.md
> Fix evan-biederstedt.md

- _members/erica-stutz.md
- _members/jennifer-chen.md
- _members/julian-zulueta.md
- _members/siyoung-kim.md
- _members/tram-nguyen.md
- _positions/sr-ui-ux-designer.md
Update 2024 summer intern statuses and add missing alumni. Fix career site link for Senior UI/UX posting.
closes #403
> Update lab membership status and posting application link

- _positions/postdoc-biomedical-data-viz.md
> Update Postdoctoral Fellow positions for lab website.

- .github/ISSUE_TEMPLATE/news.yml
- .github/workflows/create-news.yml
- scripts/create-hidive-news.ts
- scripts/update-hidive-paper.ts
Add a script and automation for adding news updates to the lab website
Example: https://github.com/manzt/gehlenborglab-website/issues/1
> Create annoucement automation

- .github/ISSUE_TEMPLATE/new-member.yml
- .github/workflows/add-lab-member.yml
- scripts/create-hidive-member.ts
- scripts/create-hidive-news.ts
- scripts/update-hidive-paper.ts
- scripts/util.ts
Adds an issue template (and GitHub Action) to add a lab member to the website
example: https://github.com/manzt/gehlenborglab-website/pull/6
> Create lab member automation

- .github/ISSUE_TEMPLATE/new-member.yml
- scripts/create-hidive-member.ts
This was an oversight on my part. Lab members may or may not have a degree (yet) and it should be an optional field.
> Make degree field optional for template

- _news/2021-04-15-goldwater-scholarship.md
> add news story for goldwater scholarship karan

- _news/2025-03-07-vues.md
- scripts/create-hidive-news.ts
Fixes issue https://github.com/hms-dbmi/gehlenborglab-website/issues/776
> fix: Use `members` instead of `lab_members` in issue template

- .github/ISSUE_TEMPLATE/new-member.yml
Adds a required validation for image alt text (like the image itself).
> Fix new member issue template

- _members/astrid-vandenbrandt.md
- _members/emily-hang.md
- _members/etowah-adams.md
Changes to keep the team members page up to date.
> update members: Astrid, Emily, Etowah

- _news/2025-03-07-vues.md
- _news/2025-03-11-chi-visual-problem-solving.md
Fix typo on VUES announcement and link to Visual Problem Solving publication.
> Minor updates to news. 

- _publications/lyi-2024-F8FYKQP6.md
This PR updates the accessibility evaluation paper based on it's publication to Scientific Reports
> Update the a11y Scientific Reports paper
