_data/media.yml, _layouts/member.html, _layouts/project.html
@ngehlenborg ? Towards #79 
Here's what it looks like on the member page and the project page:
(This is actually just jekyll data, rather than a "collection", since we do not want any stand-alone pages for these.)
Even assuming it looks ok, should probably get more items in there before releasing:
- Probably do not actually want to list UpSet press for UpSetR?
- Do we only want to list media relating to projects, or are we interested in other citations (https://www.google.com/search?q=nils+gehlenborg&tbm=nws) that present you or other lab members as knowledgeable people?
=> media on members and projects

_layouts/publication.html
Notice the italics and bold in the citation:
=> Fix #90: Process markdown in citation on publication page.

assets/main.scss, projects.md
@ngehlenborg : It looks like this right now... It could be merged, or you can wait till more projects have images. Fix #146.
=> Thumbnails on projects page

_projects/higlass.md
The higlass docker container now resides in the higlass namespace.
=> Update location of higlass docker container

.gitignore, package-lock.json
Best practice is not to ignore package-lock.json.
In package.json, all we have is 
```
"dependencies": {
"bitters": "^3.0.0",
"bourbon": "^6.0.0",
"uswds": "^1.2.1"
},
```
If any of those released a minor update, our site could change unpredictably with the next build. package-lock.json will guarantee that we get the same version.
(Alternatively, we could pin to an exact version in package.json.)
=> Stop ignoring package-lock.json

letters-of-recommendation.md
The `1.` is translated to `<li>` in a `<ol>`. If you strongly prefer that the sublists be a. / b. / c. that's a CSS change... which isn't impossible, but I think lots of other things are more important right now.
=> add letters of recommendation

.github/workflows/deploy.yml
Some of the docs referenced an older version, this fix the ruby setup.
=> Update ruby workflow

_publications/manz-2020-osfpreprint.md
Fixing broken link that I ran into looking up your Viv code. `githubcom` needed to be changed to `github.com`
=> Fix broken link in manz-2020-osfpreprint.md

_news/2020-08-13-viv-preprint.md, _news/2022-05-11-viv-paper-nature-methods.md, _projects/hubmap.md, _projects/viv.md, _publications/manz-2022-viv-nature-methods.md
- replaces `_publications/2020-manz-osfpreprint.md` with `_publications/2022-manz-viv-nature-methods.md`
- updates old references to preprint with publication
- adds `_news/` entry announcing Viv's Nature Methods publication
=> chore: add Viv publication in Nature Methods

.github/workflows/deploy.yml
Reinstating cache after successful workflows. Upon further investigation, the `sassc` installation needed to be configured to work with Github Actions reliably.
=> Reinstate cache

publications.md
Currently, 'preprints' is an h1 element, and all the other years are h2 elements. The 'preprints' and '2024', '2023', etc., should be the same level.
=> Add global h1 to publications and change preprints back to h2

cloudformation/static-site.yaml
When I tried to run the `static-site.yaml`, I got the following error. 
> An error occurred (ValidationError) when calling the CreateStack operation: Template format error: YAML not well-formed. (line 213, column 2)
```
_# This function replicates the Amazon S3 behavior that directs any request that lacks a filename to index.html,
_# regardless of whether it's for the root of a website or a subfolder.
_# https://github.com/aws-samples/amazon-cloudfront-functions/tree/main/url-rewrite-single-page-apps
_CloudFrontFunction: ← Line 213, one space for indentation seems to be the issue
```
=> Fix YAML format

_publications/manz-cev-2024.md
Copied the `published` from another entry and forgot to update. Thanks @EricMoerthVis
=> fix: Use correct preprint link for CEV

scripts/update-hidive-paper.ts
I noticed some of my drag-and-dropped images did not appear in the corresponding PR. Sometimes github produces markdown image tags upon drag-and-drop
=> Parse markdown img tag

.github/ISSUE_TEMPLATE/new-member.yml
The text for `<img>` / `![<alt>]()` doesn't display correctly because it's
rendered as markdown. This PR escapes the markdown so that the text is
displayed correctly.
=> Escape HTML im members template description

_includes/publication-row.html
The alt text in the publications row template isn't appropriately escaped, so
it's breaking the generated HTML and there is a bad layout shift/bug on the
site. This PR fixes that by escaping the alt text in the publications row
template.
Example:
The `'` in "Don't" breaks the quoting and the image tag.
=> Escape title in publication image alt text

scripts/update-hidive-paper.ts
Sorry if I am missing something. It looks like we are not showing the `<TODO>` list anymore, but I see a related description in the PR created automatically.
=> Remove a description about `<TODO>`

.github/workflows/update-paper.yml
Adds a consistent prefix to paper-bot PRs. PRs from this automation will now be titled: "paper-bot: Update \<zotero-id\>"
=> Add paper-bot: prefix to automated PRs

_includes/publication-row.html
Update the `ul.icon-list` in the `_includes/publication-row.html` file to remediate a `Container element is empty` WCAG Level A issue (125 occurrences)
> A container element for an unordered list,` <ul>`, should not exist without the list items, `<li>`. 
>
> ## Who is impacted by this barrier?
> 
> When elements are correctly grouped, blind or low-vision screen reader users are able to easier understand the contexts and structures that are present on the website. If the content is not properly structured, navigating the website can be very confusing. For instance, if you encounter a list on the website, you would expect it to have list items. Otherwise, you might wonder if some information is hidden or missing.
=> WCAG level A: container elements such as UL must not be empty

_layouts/member.html, _layouts/news.html, _layouts/project.html, _layouts/publication.html, _layouts/team.html, assets/main.scss, funding.md, index.md, members.md, news.md, open-positions.md, projects.md, themes.md
> Heading tags help assistive technology users to understand how content is structured. They're also used for in-page screen reader navigation.
> 
> When adding heading tags, we should ensure that they follow a nested structure. `<h1>` is used for the primary heading, followed by `<h2>` for subheadings, and so on to `<h6>`.
> 
> ## Who is impacted by this barrier?
> 
> When page content is organized using headings, all users are able to skim through the content easily and get a sense of how the content is structured. Screen readers and assistive technologies rely on heading tags (\<h1> - \<h6>) to identify headings. If the heading skips a level, the user might wonder if they are missing some important content or context. If the text is only enlarged, bolded, or emphasized, but the correct …
=> Structured Headings (Accessibility best practice)

_teams/accessibility/index.md, _teams/accessibility/mental-models-blv.md
Site will be broken until this is approved.
The changes introduced in #549 break the site because the old slug used
for the preprint is no longer available. This PR updates the slug for
the corresponding pages.
=> fix: Replace old BLV slug with new

_members/chris-briggs.md, _members/cynthia-rosas.md, _members/emily-hang.md, _members/evan-biederstedt.md, _members/furui-cheng.md, assets/members.csv, scripts/create-hidive-member.ts, scripts/export-lab-members.ts
Adds script `./scripts/export-lab-members.ts` which:
1.) Parses and validates member metadata from `_members`
2.) Prints the data serialized to `.csv` format to stdout
I have checked in the output of the file into `assets/member.csv`
```sh
deno run -A scripts/export-lab-members.ts > assets/members.csv
```
Members with invalid metadata will be printed nicely to the console to help with resolving these data quality issues.
=> Export lab members to `members.csv`

assets/members.csv, scripts/export-lab-members.ts
Also updates script to write the `assets/members.csv` directly (instead of a requiring pipe) and ignores template.
=> Re-export members to include George

.github/ISSUE_TEMPLATE/paper.yml, scripts/update-hidive-paper.ts
The auto generated name for publications took the form: `<year>-<author-last>-<zotero-key>.md`
This PR adds a form entry for "slug", or an optional field for the user to specify a replacement for the `<zotero-key>` in the identifier above.
This can make the papers easier to find and URL easier to remember on the website.
=> Allow specifying slug for papers for more/memorable readable URLs

_sass/_variables.scss
This PR switches from using rsms's CDN for Inter font to Google Fonts.
I've had a consistent issue with Inter loading from rms's CDN without cache (requests just hangs), leading to long page loading spinner and unstyled content.
Now that inter is on Google Fonts, I think we should switch to using it there since it is much more reliable CDN and faster.
Example of unstyled content:
=> Switch to Google Fonts for Inter font

assets/members.csv, scripts/export-lab-members.ts
The `jsr:@std/csv` library omits the trailing comma when the **last
field** is `null`, causing inconsistent row lengths. I believe this is a
subtle bug with `[].join(",")`. Instead of modifying how null values are
handled, this quick fix switches the order of `start` and `end` so that
`start` (which is always defined) is the last field.
We should probably use a different library but this works. Since empty
strings in inner fields are correctly encoded as `,,`, this ensures
uniform column counts across all rows.
=> fix: Reorder CSV columns to ensure consistent trailing commas

.github/ISSUE_TEMPLATE/news.yml, scripts/create-hidive-news.ts
> Maybe the template can be revised to allow setting a date
> We often don’t get to making the announcement when it happens
\- Nils
(and also easier for a backfill)
=> add optional date to news issue template

.github/workflows/ci.yml, .gitignore, scripts/deno.json
I've been manually typechecking these scripts across various PRs
locally, but we haven't had any automated checks for them.
Now that others are contributing, this action helps maintain code
quality going forward by ensuring all `.ts` files in `scripts/` are
checked consistently.
=> typecheck/lint/format `./scripts/*.ts` in CI

.github/ISSUE_TEMPLATE/new-member.yml, .github/ISSUE_TEMPLATE/paper.yml, .github/workflows/ci.yml, scripts/create-hidive-member.ts, scripts/update-hidive-paper.ts
Adds explicit input for image alt text to the paper issue form. I'd like to defer to @LDubya @thomcsmits @sehilyi if we can/how to include better guidelines around how to write alt text.
=> Add explicit input for alt text in paper form

.github/workflows/deploy.yml
Updates the Ubuntu version used for deploying the lab website.
Caveats:
- haven't tested or researched compatibility of any of the dependencies.
- this is the last workflow that uses a fixed Ubuntu version (other use `ubuntu-latest`). Could be because of previous issues with compatibility when Github bumps the Ubuntu version for GA?
=> CI: switch to Ubuntu 24.04 for `deploy` workflow

docs/UPDATING_VIA_GIT.md
Filepath for adding images to the website needed to include the /fullsize directory to run with copy/paste! Not sure why line 70 has an insertion/deletion, but it stayed the same.
=> Update UPDATING_VIA_GIT.md to have correct filepath for images

_publications/lange-2025-yac.md
I messed up the normal publication update process (I have two similar papers). I put then content for one paper into the other. This fixes that mistake.
=> update YAC publication page to refer to the correct paper
